### ISSUE TITLE
Consistent server error

### ISSUE THREAD

**Issue by maximusunc** [suihuanglab/spoke-kp#14] opened 2024-03-21 15:57 UTC
The following request returns a server error:
```text
curl -X POST https://spokekp.healthdatascience.cloud/api/v1.4/query \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "message": {
    "query_graph": {
      "nodes": {
        "sn": {
          "categories": ["biolink:ChemicalEntity"],
          "is_set": false,
          "constraints": []
        },
        "on": {
          "ids": ["DOID:2377"],
          "categories": ["biolink:Disease"],
          "is_set": false,
          "constraints": []
        }
      },
      "edges": {
        "edge_0": {
          "subject": "sn",
          "object": "on",
          "predicates": ["biolink:ameliorates"],
          "attribute_constraints": [],
          "qualifier_constraints": []
        }
      }
    }
  },
  "submitter": "infores:aragorn"
}
' > spoke_response.json
```

**Comment by maximusunc** [comment] 2024-03-21 15:58
I also get 503 Service Temporarily Unavailable errors fairly consistently.

**Comment by brettasmi** [comment] 2024-03-21 19:01
Sent earlier via Slack:


> Hi Max, thanks for this report
> 
> 
> That is our dev environment, so it can be fairly unreliable as things are changing. This will be especially true in the next month or so.
> The ITRB envs are 
> [spokekp.transltr.io](http://spokekp.transltr.io/)
> [spokekp.test.translatr.io](http://spokekp.test.translatr.io/)
> [spokekp.ci.translatr.io](http://spokekp.ci.translatr.io/)
>

**Comment by brettasmi** [comment] 2024-03-22 04:35
@maximusunc , I was able to take a closer look at this tonight.

We use biolink-model-toolkit to descend the hierarchy to find all supported descendants of a given predicate. I believe this is required behavior in Translator. In this specific case, the use of `biolink:ameliorates` throws an error for "not a valid biolink component." I think this is because `ameliorates` is only an alias of `biolink:ameliorates_condition`. Using `biolink:ameliorates_condition` allows the query to proceed further, but only to a more helpful error message that SPOKE KP doesn't support that predicate.

Our [meta KG](https://smart-api.info/ui/7f70cdfaeb801501da08dacc294e8b9f#/meta_knowledge_graph/get_meta_knowledge_graph) returns a more reliable set of predicates that you can expect to work with SPOKE KP.

I'll close this ticket now, because I don't believe this to be a SPOKE KP issue. I will follow up with the biolink model toolkit maintainers to see if throwing an error on an alias is expected behavior or a bug.

**Closed as completed by brettasmi** 2024-03-22 04:35 UTC
